name: send_whatsapp
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  davinci: ^2.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  font_awesome_flutter: ^10.7.0
  glassmorphism: ^3.0.0
  google_fonts: ^5.1.0
  home_widget: ^0.7.0
  intl: ^0.19.0
  path: ^1.8.3
  path_provider: ^2.1.4
  sqflite: ^2.3.2
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
